basic:
    name: 'https://beatitudescampus.org/'
    environments:
        production: 'https://beatitudescampus.org/'
        staging: 'https://ompnhjys9n.wpdns.site/'
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: null
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /blog
        - /events
        - /giving
        - /resources
        - /title-vi
        - /ada
        - /about
        - /independent-living
        - /independent-living/entrance-fee
        - /independent-living/rentals
        - /independent-living/expansion
        - /lifestyle
        - /lifestyle/dining
        - /lifestyle/lifelong-learning
        - /lifestyle/spiritual-life
        - /lifestyle/residents-amplified
        - /assisted-living
        - /assisted-living/residences
        - /assisted-living/home-care
        - /healthcare
        - /healthcare/memory-support
        - /healthcare/skilled-nursing-care
        - /healthcare/rehabilitation
        - /gallery
        - /contact-us
        - /cost-calculator
        - /blog/the-joy-of-downsizing-in-retirement
        - /blog/what-is-independent-living
        - /blog/comfort-matters-inside-the-heart-of-memory-care
        - /privacy-policy
        - /data-security
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: false
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 30
    night_mode: false
    retina_images: false
    single_ip: false
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
